server:
  port: 9090
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_news
    username: root
    password: 123456
mybatis:
  mapper-locations: mapper/*.xml
pagehelper:
  helper-dialect: mysql
  reasonable: true